### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by rettichschnidi** [rettichschnidi/politkarma#3]
For some reason, the Travis build fails: https://travis-ci.org/rettichschnidi/politkarma/builds/105630181

Do you know how to fix this?

**Comment by shuegli** [comment]
`Your test run exceeded 120 minutes. `

**Comment by rettichschnidi** [comment]
I just have [contacted](http://www.parlament.ch/e/kontakt/pages/default.aspx) parlament.ch. Let's see if there is a faster way to get the data.

**Comment by rettichschnidi** [comment]
> Sehr geehrter Herr S.
> 
> Wir danken Ihnen für Ihre Anfrage.
> 
> Diese Webservice-Schnittstelle ist der einzige Zugang zu unseren Daten. Eine Alternative können wir leider nicht anbieten.
> 
> Die WS werden übrigens zur Zeit neu programmiert und werden Mitte des Jahres zugänglich sein.
> 
> Wir danken für Ihr Verständnis.
> 
>  Freundliche Grüsse,
> D. S.

**Comment by rettichschnidi** [comment]
Thanks for fixing the build with commit 3f882050f488eea64344ad1ef779bd6ba31ae9f6
