### ISSUE TITLE
Build error: sqlite3.OperationalError: too many SQL variables

### ISSUE THREAD

**Issue by rettichschnidi** [rettichschnidi/politkarma#6]
How can we fix [this](https://travis-ci.org/rettichschnidi/politkarma/builds/110811236#L2949)? Migrate to PostgreSQL?

**Comment by shuegli** [comment]
The sql statements generated by django contain bind variables and the number of bind variables in this version of sqlite is [limited](https://www.sqlite.org/limits.html) to 999. The value can be reduced but not increased at run-time.
On my machine (Ubuntu 14.04 / trusty, sqlite3 version 3.8.2) the problem does not occur (this version of sqlite probably uses a higher limit).
I set the runtime environment to [trusty](https://docs.travis-ci.com/user/trusty-ci-environment/) to be able to use the same [version](https://travis-ci.org/rettichschnidi/politkarma/builds/109953914#L252) of sqlite for our build.
The [trusty build environment](https://docs.travis-ci.com/user/trusty-ci-environment/) requires sudo (not sure why). If not set, [12.04](https://travis-ci.org/rettichschnidi/politkarma/builds/110811236#L13) is used.

Trusty env is still beta, the [build](https://travis-ci.org/rettichschnidi/politkarma/builds/109953914) was stopped and restarted several times until it timed out after ~50 minutes.

I will trigger another trusty build. If we hit the timeout again, we will have to use another db.

**Comment by shuegli** [comment]
[Build](https://travis-ci.org/rettichschnidi/politkarma/builds/111065733) timed out.

**Comment by rettichschnidi** [comment]
PostgreSQL is it then?

**Comment by shuegli** [comment]
Trying a possible [workaound](https://github.com/rettichschnidi/politkarma/commit/23a3ce6a8291fbb8b9c7038dba109fa73d2d5769)...

**Comment by rettichschnidi** [comment]
Good luck :)

**Comment by shuegli** [comment]
I've changed the batch updates in `update_affair_details.py` to `save()` calls. The [build](https://travis-ci.org/rettichschnidi/politkarma/builds/111611951) ran without errors.
The only problem is that it took ~97 minutes. If we enabled `update_affair_details.py` in the build script (and the data was available :), we would probably hit the 120 min limit.
